### ISSUE TITLE
10.0.2 Error

### ISSUE THREAD

**Issue by Masumia** [Jaliborc/PetTracker#311] opened 2022-11-17 18:06 UTC
**Running Software (issues missing this information will be deleted):**
 - Addon version:
 - Server patch: [e.g. Build 8.0.1.27178]

 **Have you read the changelog? (please don't waste our time)**
 Yes

**Describe the bug**
Click on a pet trainer, bug happens

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any pet trainer
2. Click on trainer
3. See error

**Expected behaviour**
No error should happen when clicking on trainer

**Error Logs**
1x ...ce/AddOns/PetTracker/addons/main/features/gossip.lua:28: attempt to call global 'GossipFrame_GetTitleButtonCount' (a nil value)
[string "@Interface/AddOns/PetTracker/addons/main/features/gossip.lua"]:28: in function <...ce/AddOns/PetTracker/addons/main/features/gossip.lua:23>
[string "=[C]"]: in function `Update'
[string "@Interface/FrameXML/GossipFrame.lua"]:66: in function `HandleShow'
[string "@Interface/FrameXML/CustomGossipFrameBase.lua"]:47: in function `HandleOpenEvent'
[string "@Interface/FrameXML/CustomGossipFrameBase.lua"]:39: in function <Interface/FrameXML/CustomGossipFrameBase.lua:37>

Locals:
unit = "Creature-0-3885-1116-22-87122-00007418A9"
id = 87122
(*temporary) = nil
(*temporary) = "attempt to call global 'GossipFrame_GetTitleButtonCount' (a nil value)"
Addon = <table> {
 SendSignal = <function> defined @Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 Gossip = <table> {
 }
 SpeciePin = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 Enemy = <table> {
 }
 sets = <table> {
 }
 state = <table> {
 }
 MaxLevel = 25
 GetColor = <function> defined @Interface/AddOns/PetTracker/addons/main/main.lua:66
 Entity = <table> {
 }
 Species = <table> {
 }
 Delaying = <function> defined @Interface/AddOns/PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 JournalSlot = <table> {
 }
 Rival = <table> {
 }
 Tooltips = <table> {
 }
 OnPetsChanged = <function> defined @Interface/AddOns/PetTracker/addons/main/main.lua:53
 NewModule = <function> defined @Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 MultiTip = <table> {
 }
 MapCanvas = <table> {
 }
 Tracker = <table> {
 }
 Stables = <table> {
 }
 AbilityDisplay = <table> {
 }
 TextLine = <table> {
 }
 Search = <function> defined @Interface/AddOns/PetTracker/addons/main/api/search.lua:26
 StablePin = <table> {
 }
 RivalInfo = <table> {
 }
 Pin = <table> {
 }
 Delay = <function> defined @Interface/AddOns/PetTracker/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 Tag = "PETTRACKER_"
 BattleSlot = <table> {
 }
 Pet = <table> {
 }
 AbilityAction = <table> {
 }
 TextList = <table> {
 }
 MaxQuality = 6
 UnregisterMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 ProgressBar = <table> {
 }
 SpecieStats = <table> {
 }
 RivalPin = <table> {
 }
 MapSearch = <table> {
 }
 Specie = <table> {
 }
 PetSlot = <table> {
 }
 Ability = <table> {
 }
 Rivals = <table> {
 }
 Base = <table> {
 }
 Predict = <table> {
 }
 UnregisterSignal = <function> defined @Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 Maps = <table> {
 }
 SpecieBreeds = <table> {
 }
 RegisterMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 RegisterEvent = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 OnBattle = <function> defined @Interface/AddOns/PetTracker/addons/main/main.lua:57
 Breeds = <table> {
 }
 AbilityButton = <table> {
 }
 OnEnable = <function> defined @Interface/AddOns/PetTracker/addons/main/main.lua:26
 Name = "PetTracker"
 RivalOrder = <table> {
 }
 SendMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 RegisterSignal = <function> defined @Interface/AddOns/PetTracker/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterEvent = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Objectives = Frame {
 }
}
L = <table> {
 Switcher = "Switcher"
 Tutorial = <table> {
 }
 BreedExplanation = "Determines how stats gained at each level are distributed."
 FAQDescription = "These are the most frequently asked questions. To see the tutorials again, reset the addon settings using the "Defaults" button at the lower left corner."
 FilterSpecies = "Filter Species"
 Species = "Species"
 OptionsDescription = "These options allow you to toggle PetTracker general features on and off. Gotta catch them all!"
 Maximized = "Maximized"
 SpecieIconsTip = "If disabled, pets will be marked by their type instead of species when shown in the world and battle map."
 TotalRivals = "Total Rivals"
 Ninja = "Ninja"
 AddWaypoint = "Add Waypoint"
 AvailableBreeds = "Available Breeds"
 ShowStables = "Show Stables"
 Breed = "Breed"
 Source8 = "Promotion"
 TellMore = "Tell me more about yourself."
 AlertUpgrades = "Alert for Upgrades"
 NoneCollected = "None Collected"
 EnemyTeam = "Enemy Team"
 S

**Comment by GurliGebis** [comment] 2022-11-18 16:09
This issue is a duplicate of #299.
The fix is in PR #308

**Comment by GurliGebis** [comment] 2022-11-18 19:31
The correct fix for this is in #312 - instead of checking if the function exists (which it never will), just change it to use the correct function instead.

**Comment by GurliGebis** [comment] 2022-11-18 19:58
My bad, it seems like #299 is better until a better solution can be found.

**Closed** 2023-02-07 16:35 UTC
